name: Changeset

on: 
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changeset:
    if: ${{ github.event.label.name != 'no-changeset' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Check if changeset is added
        run: |
          git pull -f origin main:main
          npm i -g @changesets/cli@2.22.0
          changeset status --verbose
