# # https://github.com/vercel/next.js/commits/canary/.github/workflows/build_test_deploy.yml

# name: CI

# on:
#   pull_request:
#     types: [opened, synchronize]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os:
#           - ubuntu-latest
#           - windows-latest
#         node_version:
#           - 16
#     name: Node ${{ matrix.node_version }} - ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
#         with:
#           version: 6.32.6
#       - name: Setup node
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node_version }}
#           cache: "pnpm"
#       - run: pnpm install --frozen-lockfile
#       - run: pnpm manypkg check
#       - run: pnpm build
#       - run: pnpm lint
#       - run: pnpm build:apps
#       - run: pnpm test
name: CI

on:
  push:
    branches: [main]

jobs:
  directories: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
        run: cd integration-tests
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above'
        run: echo "::set-output name=dir::$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named dir base on ls command transformed to JSON thanks to jq
  loop:
    runs-on: ubuntu-latest
    needs: [directories] # Depends on previous job
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} # List matrix strategy from directories dynamically
    steps:
      - run: echo ${{matrix.dir}}
